### ISSUE TITLE
refreshing while transmitting audio crashes server

### ISSUE THREAD

**Issue by Jrawke** [Jrawke/mumbleExpress#24] opened 2015-12-18 00:27 UTC

**Comment by Jrawke** [comment] 2015-12-18 01:23
```
Error: write after end
    at writeAfterEnd (_stream_writable.js:130:12)
    at CleartextStream.Writable.write (_stream_writable.js:178:5)
    at MumbleSocket.write (/home/owen/Documents/mumbleExpress/node_modules/mumble/lib/MumbleSocket.js:66:17)
    at EventEmitter.MumbleConnection.sendEncodedFrame (/home/owen/Documents/mumbleExpress/node_modules/mumble/lib/MumbleConnection.js:347:17)
    at EventEmitter.MumbleConnection.sendVoiceFrame (/home/owen/Documents/mumbleExpress/node_modules/mumble/lib/MumbleConnection.js:260:23)
    at Writable.MumbleInputStream._processBuffer (/home/owen/Documents/mumbleExpress/node_modules/mumble/lib/MumbleInputStream.js:127:33)
    at wrapper [as _onTimeout] (timers.js:252:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
```

**Comment by tomKPZ** [comment] 2015-12-18 02:03
Closing this because it's a duplicate of #22

**Closed by tomKPZ** 2015-12-18 02:03 UTC

**Comment by Jrawke** [comment] 2015-12-18 02:04
:+1:
